"""Launch the complete official DSH Web; never translate its session protocol."""
import json
import os
import re
import shutil
import signal
import subprocess
import tempfile
import threading
import time
from pathlib import Path
from urllib.parse import urlsplit

from dotenv import load_dotenv


def web_distribution():
    candidates = [Path(os.environ['DSH_WEB_DIR'])] if os.getenv('DSH_WEB_DIR') else [Path.cwd(), Path(__file__).resolve().parent.parent]
    for root in candidates:
        root = root.resolve()
        package = root / 'node_modules/@deepseek-ai/dsh'
        if (package / 'lib/bin.js').is_file():
            metadata = json.loads((package / 'package.json').read_text())
            if metadata['version'] != '0.2.0-rc.2':
                raise RuntimeError('官方 Web 版本不匹配，请在仓库根目录运行 npm ci')
            node = shutil.which('node')
            if not node: raise RuntimeError('官方 Web 需要 Node.js 22.19+，推荐 Node.js 24')
            return node, str(package / 'lib/bin.js')
    raise RuntimeError('缺少官方 Web 发行包。请在仓库根目录运行 npm ci，或设置 DSH_WEB_DIR 指向已安装目录')


def public_url(value):
    url = urlsplit(value)
    if url.scheme not in ('http', 'https') or not url.hostname or url.username or url.password or url.path not in ('', '/') or url.query or url.fragment:
        raise ValueError('WORKBENCH_PUBLIC_URL 必须是无路径、无凭据的 HTTP(S) origin')
    # Also validates a supplied port and excludes Nginx configuration characters.
    _ = url.port
    if not re.fullmatch(r'[A-Za-z0-9.\-:\[\]]+', url.netloc):
        raise ValueError('WORKBENCH_PUBLIC_URL 主机不合法')
    return value.rstrip('/'), url.netloc


def nginx_config(port, upstream_port, temp_dir):
    if not (1 <= port <= 65535 and 1 <= upstream_port <= 65535) or port == upstream_port:
        raise ValueError('代理端口和官方 Web 内部端口必须不同，且位于 1..65535')
    # Paths are generated by us; quote to support spaces in a system temp directory.
    root = str(Path(temp_dir)).replace('\\', '/').replace('"', '\\"')
    # Root test environments can have no mapped nobody uid. Container runs non-root.
    user = 'user root;\n' if hasattr(os, 'geteuid') and os.geteuid() == 0 else ''
    return f'''{user}worker_processes 1;
pid "{root}/nginx.pid";
error_log stderr warn;
events {{ worker_connections 1024; }}
http {{
    access_log off;
    client_body_temp_path "{root}/body";
    proxy_temp_path "{root}/proxy";
    fastcgi_temp_path "{root}/fastcgi";
    uwsgi_temp_path "{root}/uwsgi";
    scgi_temp_path "{root}/scgi";
    map $http_upgrade $connection_upgrade {{ default upgrade; '' close; }}
    server {{
        listen 0.0.0.0:{port};
        client_max_body_size 100m;
        location / {{
            proxy_pass http://127.0.0.1:{upstream_port};
            proxy_http_version 1.1;
            proxy_set_header Host $http_host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Origin $http_origin;
            proxy_set_header X-Forwarded-Proto $scheme;
            # No browser origin or credential substitution: official trust stays authoritative.
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
            proxy_redirect off;
        }}
    }}
}}
'''


def stop_process(process):
    if process is None or process.poll() is not None: return
    try:
        if os.name == 'posix': os.killpg(process.pid, signal.SIGTERM)
        else: process.terminate()
    except ProcessLookupError:
        return
    try: process.wait(timeout=8)
    except subprocess.TimeoutExpired:
        if os.name == 'posix': os.killpg(process.pid, signal.SIGKILL)
        else: process.kill()
        process.wait(timeout=5)


def serve(host, port, upstream_port=18765, trusted_hosts=()):
    load_dotenv()
    node, entry = web_distribution()
    if host not in ('127.0.0.1', 'localhost', '0.0.0.0'):
        raise ValueError('本版支持 localhost/127.0.0.1；0.0.0.0 仅用于容器 Nginx 入口')
    if not 1 <= port <= 65535: raise ValueError('端口必须位于 1..65535')
    proxy = host == '0.0.0.0'
    exposed, authority = public_url(os.getenv('WORKBENCH_PUBLIC_URL', f'http://localhost:{port}'))
    data = Path(os.getenv('WORKBENCH_DATA_DIR', './data')).resolve()
    home = Path(os.getenv('WORKBENCH_WEB_HOME', str(data / 'web/dsh-home'))).resolve()
    workspace = Path(os.getenv('WORKBENCH_WEB_WORKSPACE', str(data / 'web/workspace'))).resolve()
    home.mkdir(parents=True, exist_ok=True); workspace.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy(); env['DSH_HOME'] = str(home); env['WORKBENCH_PUBLIC_URL'] = exposed
    bootstrap = home / 'workbench-web.patch.json'
    patches = [{'id':'workspace-controller','config':{
        'documentsDirectory':str(workspace),'documentsLookupTimeoutMs':10000}}]
    embed_value = os.getenv('WORKBENCH_EMBED_ENABLED', 'false').strip().lower()
    if embed_value not in ('true', 'false', '1', '0', ''):
        raise ValueError('WORKBENCH_EMBED_ENABLED 必须是 true/false 或 1/0')
    extensions_enabled = bool(os.getenv('WORKBENCH_WORKSPACE_CONFIG')) or embed_value in ('true', '1')
    if extensions_enabled:
        extension = Path(__file__).resolve().parent.parent / 'node_modules/@dsh-workbench/extensions/package.json'
        if not extension.is_file():
            raise RuntimeError('工作台扩展未安装，请在仓库根目录运行 npm ci')
        # A file URL bypasses profile package-governance for this repository-owned
        # plugin; client-modules still discovers its nearest package.json.
        patches.append({'insert':[{'id':'workbench-extensions','name':(extension.parent / 'src/index.js').as_uri()}]})
    if embed_value in ('true', '1'):
        if not os.getenv('WORKBENCH_WORKSPACE_CONFIG') or not os.getenv('WORKBENCH_EMBED_CONFIG'):
            raise ValueError('启用嵌入时必须设置 WORKBENCH_WORKSPACE_CONFIG 和 WORKBENCH_EMBED_CONFIG')
        patches.append({'id':'connection','config':{'cookieSecure':urlsplit(exposed).scheme == 'https'}})
    bootstrap.write_text(json.dumps(patches,ensure_ascii=False))
    nginx = None
    if proxy:
        nginx = shutil.which('nginx')
        if not nginx: raise RuntimeError('0.0.0.0 入口需要 Nginx，请使用本仓库 Docker 镜像；本地运行请省略 --host')
    internal = upstream_port if proxy else port
    command = [node, entry, '--profile', 'web', '--patch', str(bootstrap)]
    for patch in os.getenv('DSH_WEB_PATCHES','').split(os.pathsep):
        if patch: command += ['--patch',str(Path(patch).resolve())]
    command += ['--host', '127.0.0.1', '--port', str(internal), '--no-open']
    for authority_value in dict.fromkeys([authority, f'localhost:{port}', f'127.0.0.1:{port}', *trusted_hosts]):
        if not re.fullmatch(r'[A-Za-z0-9.\-:\[\]]+', authority_value): raise ValueError('trusted-host 不合法')
        command += ['--trusted-host', authority_value]
    ready = threading.Event()
    extension_failed = threading.Event()
    native = front = None
    stopping = threading.Event()
    def interrupt(signum, frame): stopping.set()
    old_handlers = {}
    if threading.current_thread() is threading.main_thread():
        for sig in (signal.SIGINT, signal.SIGTERM):
            old_handlers[sig] = signal.signal(sig, interrupt)
    temporary_directory = tempfile.TemporaryDirectory(prefix='dsh-web-proxy-')
    temporary = temporary_directory.name
    try:
        if proxy:
            conf = Path(temporary) / 'nginx.conf'
            conf.write_text(nginx_config(port, internal, temporary))
            subprocess.run([nginx, '-t', '-c', str(conf), '-p', temporary], check=True)
        native = subprocess.Popen(command, cwd=workspace, env=env, stdout=subprocess.PIPE,
                                  stderr=subprocess.STDOUT, text=True, bufsize=1,
                                  start_new_session=os.name == 'posix')
        def output():
            for line in native.stdout:
                if extensions_enabled and 'workbench-extensions (' in line:
                    extension_failed.set()
                if re.search(r'dsh web:\s+https?://', line):
                    # The official one-time token and cookie exchange are kept unchanged.
                    if proxy:
                        line = re.sub(r'https?://(?:127\.0\.0\.1|localhost):\d+', exposed, line)
                    ready.set()
                print(line, end='', flush=True)
        threading.Thread(target=output, daemon=True).start()
        deadline = time.monotonic() + 90
        while not ready.wait(.1):
            if stopping.is_set(): return 0
            if native.poll() is not None: return native.returncode or 1
            if time.monotonic() > deadline: raise RuntimeError('官方 DSH Web 在 90 秒内未就绪，请检查上方诊断')
        if extension_failed.is_set():
            raise RuntimeError('工作台扩展未能激活，请检查上方 workbench-extensions 诊断')
        if proxy:
            front = subprocess.Popen([nginx, '-c', str(conf), '-p', temporary, '-g', 'daemon off;'],
                                     start_new_session=os.name == 'posix')
        print('完整官方 DSH Web 已启动。使用上方带一次性 token 的地址登录。', flush=True)
        while not stopping.wait(.2):
            if native.poll() is not None: return native.returncode or 1
            if front is not None and front.poll() is not None: return front.returncode or 1
        return 0
    finally:
        # Close frontend before backend, including when either one fails to start.
        stop_process(front)
        stop_process(native)
        temporary_directory.cleanup()
        for sig, handler in old_handlers.items(): signal.signal(sig, handler)
