import json
import sqlite3
import uuid
from pathlib import Path

class Store:
    def __init__(self, root: Path):
        self.root = root
        root.mkdir(parents=True, exist_ok=True)
        self.db = root / 'workbench.sqlite3'
        with self.connect() as c:
            c.executescript('''
            PRAGMA journal_mode=WAL;
            CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY, title TEXT, created TEXT DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS runs(id TEXT PRIMARY KEY, session_id TEXT, prompt TEXT, state TEXT, response TEXT DEFAULT '', reason TEXT, created TEXT DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT, run_id TEXT, kind TEXT, payload TEXT);
            CREATE INDEX IF NOT EXISTS events_run_id ON events(run_id,id);
            ''')
            c.execute("UPDATE runs SET state='interrupted', reason='Server restarted before completion' WHERE state='running'")

    def connect(self):
        c = sqlite3.connect(self.db, timeout=10)
        c.row_factory = sqlite3.Row
        return c

    def create_session(self, title='新会话'):
        sid = uuid.uuid4().hex
        with self.connect() as c:
            c.execute('INSERT INTO sessions(id,title) VALUES(?,?)', (sid, title))
        self.workspace(sid).mkdir(parents=True)
        return {'id': sid, 'title': title}

    def sessions(self):
        with self.connect() as c:
            return [dict(r) for r in c.execute('SELECT * FROM sessions ORDER BY created DESC, rowid DESC')]

    def require_session(self, sid):
        with self.connect() as c:
            if not c.execute('SELECT id FROM sessions WHERE id=?', (sid,)).fetchone():
                raise KeyError('会话不存在')

    def workspace(self, sid):
        # Only IDs generated by us may be mapped onto a directory.
        if len(sid) != 32 or any(x not in '0123456789abcdef' for x in sid):
            raise KeyError('无效会话 ID')
        return self.root / 'sessions' / sid / 'workspace'

    def new_run(self, sid, prompt):
        rid = uuid.uuid4().hex
        with self.connect() as c:
            c.execute('INSERT INTO runs(id,session_id,prompt,state) VALUES(?,?,?,?)', (rid, sid, prompt, 'running'))
        return rid

    def finish(self, rid, state, response='', reason=None):
        with self.connect() as c:
            c.execute('UPDATE runs SET state=?,response=?,reason=? WHERE id=?', (state,response,reason,rid))

    def run(self, rid):
        with self.connect() as c:
            r = c.execute('SELECT * FROM runs WHERE id=?', (rid,)).fetchone()
        if r is None: raise KeyError('任务不存在')
        return dict(r)

    def runs(self, sid):
        with self.connect() as c:
            return [dict(r) for r in c.execute('SELECT * FROM runs WHERE session_id=? ORDER BY rowid', (sid,))]

    def event(self, rid, kind, payload):
        with self.connect() as c:
            c.execute('INSERT INTO events(run_id,kind,payload) VALUES(?,?,?)',
                      (rid, kind, json.dumps(payload, ensure_ascii=False)))

    def events(self, rid, after=0):
        with self.connect() as c:
            rows = c.execute('SELECT * FROM events WHERE run_id=? AND id>? ORDER BY id LIMIT 200', (rid, after)).fetchall()
        return [dict(r) | {'payload': json.loads(r['payload'])} for r in rows]
